services:
 facefusion-cpu:
  build:
   context: .
   dockerfile: Dockerfile.cpu
  command: [ 'python', 'run.py' ]
  environment:
    PUID: 1000
    PGID: 1000
  env_file: .env
  volumes:
  - .assets:/facefusion/.assets
  ports:
  - 127.0.0.1:7870:7860
