services:
 facefusion-rocm:
  build:
   context: .
   dockerfile: Dockerfile.rocm
  command: [ 'python', 'run.py', '--execution-providers', 'rocm' ]
  environment:
    PUID: 1000
    PGID: 1000
  env_file: .env
  volumes:
  - .assets:/facefusion/.assets
  ports:
  - 127.0.0.1:7890:7860
  deploy:
   resources:
    reservations:
     devices:
     - driver: rocm
       capabilities: [ gpu, video ]
