services:
 facefusion-cuda:
  build:
   context: .
   dockerfile: Dockerfile.cuda
  command: [ 'python', 'facefusion.py', 'run', '--execution-providers', 'cuda' ]
  env_file: .env
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  ports:
  - 127.0.0.7880:7860
  deploy:
   resources:
    reservations:
     devices:
     - driver: nvidia
       count: all
       capabilities: [ gpu, video ]
